import React from 'react';
import { Ticket, Building, Users, Coins } from 'lucide-react';

interface AdminMetricsProps {
  totalTicketsCount: number;
  totalProducers: number;
  totalBuyers: number;
  totalPlatformVolume: number;
}

export default function AdminMetrics({
  totalTicketsCount,
  totalProducers,
  totalBuyers,
  totalPlatformVolume,
}: AdminMetricsProps) {
  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4" id="admin-metrics-matrix">
      {/* STAT 1: TICKETS */}
      <div className="glass-panel rounded-2xl p-5 border border-white/5 relative overflow-hidden group hover:border-rose-500/20 transition-all">
        <div className="absolute top-0 right-0 w-24 h-24 bg-rose-500/5 rounded-full blur-2xl group-hover:bg-rose-500/10 transition-all pointer-events-none" />
        <div className="flex items-center justify-between">
          <span className="text-[10px] font-mono font-bold tracking-wider text-gray-400 uppercase">
            ACTIVE HUB TICKETS
          </span>
          <div className="rounded-lg bg-rose-500/10 p-2 text-rose-400">
            <Ticket className="h-4 w-4" />
          </div>
        </div>
        <div className="mt-4">
          <span className="text-2xl font-black font-mono text-white">{totalTicketsCount}</span>
          <p className="text-[10px] text-gray-500 mt-1">Generated by all organisers</p>
        </div>
      </div>

      {/* STAT 2: PRODUCERS */}
      <div className="glass-panel rounded-2xl p-5 border border-white/5 relative overflow-hidden group hover:border-gold/20 transition-all">
        <div className="absolute top-0 right-0 w-24 h-24 bg-gold/5 rounded-full blur-2xl group-hover:bg-gold/10 transition-all pointer-events-none" />
        <div className="flex items-center justify-between">
          <span className="text-[10px] font-mono font-bold tracking-wider text-gray-400 uppercase">
            REGISTERED ORGANISERS
          </span>
          <div className="rounded-lg bg-gold/10 p-2 text-gold">
            <Building className="h-4 w-4" />
          </div>
        </div>
        <div className="mt-4">
          <span className="text-2xl font-black font-mono text-white">{totalProducers}</span>
          <p className="text-[10px] text-gray-500 mt-1">Event organisers and publishers</p>
        </div>
      </div>

      {/* STAT 3: BUYERS */}
      <div className="glass-panel rounded-2xl p-5 border border-white/5 relative overflow-hidden group hover:border-sky-500/20 transition-all">
        <div className="absolute top-0 right-0 w-24 h-24 bg-sky-500/5 rounded-full blur-2xl group-hover:bg-sky-500/10 pointer-events-none" />
        <div className="flex items-center justify-between">
          <span className="text-[10px] font-mono font-bold tracking-wider text-gray-400 uppercase">
            REGISTERED BUYERS
          </span>
          <div className="rounded-lg bg-sky-500/10 p-2 text-sky-400">
            <Users className="h-4 w-4" />
          </div>
        </div>
        <div className="mt-4">
          <span className="text-2xl font-black font-mono text-white">{totalBuyers}</span>
          <p className="text-[10px] text-gray-500 mt-1">Event fans and ticket buyers</p>
        </div>
      </div>

      {/* STAT 4: VOLUME */}
      <div className="glass-panel rounded-2xl p-5 border border-white/5 relative overflow-hidden group hover:border-emerald-500/20 transition-all">
        <div className="absolute top-0 right-0 w-24 h-24 bg-emerald-500/5 rounded-full blur-2xl group-hover:bg-emerald-500/10 pointer-events-none" />
        <div className="flex items-center justify-between">
          <span className="text-[10px] font-mono font-bold tracking-wider text-gray-400 uppercase">
            ORGANISERS REVENUE FLOW
          </span>
          <div className="rounded-lg bg-emerald-500/10 p-2 text-emerald-400">
            <Coins className="h-4 w-4" />
          </div>
        </div>
        <div className="mt-4">
          <span className="text-2xl font-black font-mono text-emerald-400">
            GH₵{totalPlatformVolume.toLocaleString()}
          </span>
          <p className="text-[10px] text-gray-500 mt-1">Accrued event payouts</p>
        </div>
      </div>
    </div>
  );
}
